<S> -> <IF>.
<IF> -> 'if' <COND> '{' <TRADE> '}' 'else' '{' <TRADE> '}' | 'if' <COND> '{' <TRADE> '}'.
<COND> -> '('<VALUE> <OP> <OBS> ')'| '('<COND><LOGOP><COND>')'.
<VALUE> -> <INTCONST> | <REALCONST>.
<OBS> -> 'ma'<MA>'['<DAY>']'|<PRICE>'['<DAY>']'.
<PRICE> -> 'open'|'high'|'low'|'close'.
<MA> -> '25'|'50'|'200'.
<DAY> -> '0'|'1'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|'9'.
<OP> -> '<'|'>'|'<='|'>='.
<AR> -> '+'|'*'|'-'.
<INTCONST> -> <INTCONST><INTCONST>|'0'|'1'|'2'|'3'|'4'|'5'|'6'|'7'|'8'|'9'.
<REALCONST> -> '0.'<INTCONST>.
<LOGOP> -> '||' | '&&'.
<TRADE> -> 'return BUY;'|'return SELL;'|'return NOTHING;'.