<CODE> -> <LINE>|<CODE> <LINE>.
<LINE> -> <ACTION> ';'|<IF>.
<IF> -> 'if' <COND> '{' <LINE> '}' 'else' '{' <LINE> '}' | 'if' <COND> '{' <LINE> '}'.
<COND> -> '(' <OBS> ')' | '(' <OBS> <OP> <OBS> ')' | '(' '(' <AREXP> ')' <OP> '(' <AREXP> ')' ')'.
<OBS> -> 'r_f_d'|'l_f_d'|'u_f_d'|'d_f_d'.
<OP> -> '<'|'>'|'<='|'>='.
<AR> -> '+'|'*'|'-'.
<ACTION> -> '"RIGHT"'|'"LEFT"'|'"UP"'|'"DOWN"'|'"NEUTRAL"'.
<V> -> '0'|'1'|'2'|'3'|'4'|'5'|'6'|'7'.
<AREXP> -> <OBS>|<V>|<AREXP> <AR> <AREXP>.
<Pi> -> '0'|'1'|'2'|'3'|'4'|'5'|'6'|'7'.
<LOGOP> -> '||' | '&&'.